FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Tristan.Six.FaceDetection.Console/Tristan.Six.FaceDetection.Console.csproj", "Tristan.Six.FaceDetection.Console/"]
RUN dotnet restore "Tristan.Six.FaceDetection.Console/Tristan.Six.FaceDetection.Console.csproj"
COPY . .
WORKDIR "/src/Tristan.Six.FaceDetection.Console"
RUN dotnet build "Tristan.Six.FaceDetection.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tristan.Six.FaceDetection.Console.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tristan.Six.FaceDetection.Console.dll"]