FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Tristan.Six.FaceDetection.WebApi/Tristan.Six.FaceDetection.WebApi.csproj", "Tristan.Six.FaceDetection.WebApi/"]
RUN dotnet restore "Tristan.Six.FaceDetection.WebApi/Tristan.Six.FaceDetection.WebApi.csproj"
COPY . .
WORKDIR "/src/Tristan.Six.FaceDetection.WebApi"
RUN dotnet build "Tristan.Six.FaceDetection.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tristan.Six.FaceDetection.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tristan.Six.FaceDetection.WebApi.dll"]